# fly.toml app configuration file generated for avatar-alex on 2026-07-10T15:44:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'avatar-alex'
primary_region = 'sjc'

[build]

[env]
  COOKIE_SECURE = '1'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 150
    soft_limit = 90

  [[http_service.checks]]
    interval = '15s'
    timeout = '3s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/config'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
